services:
  - type: web
    name: speech-to-text
    env: python
    branch: main
    plan: free
    buildCommand: |
      python -m pip install --upgrade pip
      python -m pip install -r requirements.txt
      python -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
    startCommand: python -m streamlit run app.py --server.port $PORT --server.address 0.0.0.0
